### ISSUE TITLE
Edit impacts in global assets

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#31]
A risk analysis in english you can't edit impacts of two same global asset.
Look up in [InstanceService.php#L718](https://github.com/monarc-project/zm-core/blob/master/src/MonarcCore/Service/InstanceService.php#L718)
Error
```
{
   "errors":[
      {
         "message":"Name is required",
         "error":"error-exception",
         "exception":{
            "class":"MonarcCore\\Exception\\Exception",
            "file":"\/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Model\/Entity\/AbstractEntity.php",
            "line":192,
            "message":"Name is required",
            "stacktrace":"#0 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceService.php(335): MonarcCore\\Model\\Entity\\AbstractEntity-\u003EexchangeArray(Array)\n
#1 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceService.php(756): MonarcCore\\Service\\InstanceService-\u003EupdateInstance(162, 10143, Array, Array, false)\n
#2 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceService.php(486): MonarcCore\\Service\\InstanceService-\u003EupdateBrothers(162, Object(MonarcFO\\Model\\Entity\\Instance), Array, Array)\n
#3 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/Module.php(54): MonarcCore\\Service\\InstanceService-\u003EpatchInstance(162, 10162, Array, Array, true)\n
#4 [internal function]: MonarcCore\\Module-\u003EMonarcCore\\{closure}(Object(Zend\\EventManager\\Event))\n
#5 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(490): call_user_func(Object(Closure), Object(Zend\\EventManager\\Event))\n
#6 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(214): Zend\\EventManager\\EventManager-\u003EtriggerListeners(\u0027patch\u0027, Object(Zend\\EventManager\\Event), NULL)\n
#7 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceConsequenceService.php(234): Zend\\EventManager\\EventManager-\u003Etrigger(\u0027patch\u0027, NULL, Array)\n
#8 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceConsequenceService.php(77): MonarcCore\\Service\\InstanceConsequenceService-\u003EupdateInstanceImpacts(81327, false)\n
#9 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceService.php(785): MonarcCore\\Service\\InstanceConsequenceService-\u003EpatchConsequence(81327, Array, true, true)\n
#10 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/core\/src\/MonarcCore\/Service\/InstanceService.php(342): MonarcCore\\Service\\InstanceService-\u003EupdateConsequences(162, Array, true)\n
#11 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/monarc\/frontoffice\/src\/MonarcFO\/Controller\/ApiAnrInstancesController.php(50): MonarcCore\\Service\\InstanceService-\u003EupdateInstance(162, 10162, Array)\n
#12 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractRestfulController.php(425): MonarcFO\\Controller\\ApiAnrInstancesController-\u003Eupdate(\u002710162\u0027, Array)\n
#13 [internal function]: Zend\\Mvc\\Controller\\AbstractRestfulController-\u003EonDispatch(Object(Zend\\Mvc\\MvcEvent))\n
#14 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(490): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))\n
#15 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(263): Zend\\EventManager\\EventManager-\u003EtriggerListeners(\u0027dispatch\u0027, Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n
#16 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractController.php(118): Zend\\EventManager\\EventManager-\u003EtriggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n
#17 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-mvc\/src\/Controller\/AbstractRestfulController.php(300): Zend\\Mvc\\Controller\\AbstractController-\u003Edispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n
#18 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-mvc\/src\/DispatchListener.php(118): Zend\\Mvc\\Controller\\AbstractRestfulController-\u003Edispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))\n
#19 [internal function]: Zend\\Mvc\\DispatchListener-\u003EonDispatch(Object(Zend\\Mvc\\MvcEvent))\n
#20 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(490): call_user_func(Array, Object(Zend\\Mvc\\MvcEvent))\n
#21 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-eventmanager\/src\/EventManager.php(263): Zend\\EventManager\\EventManager-\u003EtriggerListeners(\u0027dispatch\u0027, Object(Zend\\Mvc\\MvcEvent), Object(Closure))\n
#22 \/var\/lib\/monarc\/MonarcAppFO\/vendor\/zendframework\/zend-mvc\/src\/Application.php(340): Zend\\EventManager\\EventManager-\u003EtriggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))\n
#23 \/var\/lib\/monarc\/MonarcAppFO\/public\/index.php(24): Zend\\Mvc\\Application-\u003Erun()\n
#24 {main}"
         }
      }
   ]
}
```

**Comment by jerolomb** [comment]
Corrected in 5a1add2  but have to be reviewed when #7 will be done
