### ISSUE TITLE
Error when exporting analysis with Statement of Applicability

### ISSUE THREAD

**Issue by cedricbonhomme** [monarc-project/MonarcAppFO#445]
**Describe the bug**
When exporting analysis with Statement of Applicability.

**To Reproduce**

Export an analysis with a statement of applicability included in the export. Error returned:

```json
{
"errors": [
{
"message": "Call to a member function getId() on null",
"error": "error-exception",
"exception": {
"class": "Error",
"file": "/var/lib/monarc/fo/vendor/monarc/core/src/Service/AnrService.php",
"line": 471,
"message": "Call to a member function getId() on null",
"stacktrace": "#0 /var/lib/monarc/fo/vendor/monarc/core/src/Service/AnrService.php(302): Monarc\\Core\\Service\\AnrService->generateExportArray()\n#1 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAnrExportController.php(35): Monarc\\Core\\Service\\AnrService->exportAnr()\n#2 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(462): Monarc\\FrontOffice\\Controller\\ApiAnrExportController->create()\n#3 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(423): Laminas\\Mvc\\Controller\\AbstractRestfulController->processPostData()\n#4 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\\Mvc\\Controller\\AbstractRestfulController->onDispatch()\n#5 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\\EventManager\\EventManager->triggerListeners()\n#6 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#7 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(307): Laminas\\Mvc\\Controller\\AbstractController->dispatch()\n#8 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\\Mvc\\Controller\\AbstractRestfulController->dispatch()\n#9 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\\Mvc\\DispatchListener->onDispatch()\n#10 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\\EventManager\\EventManager->triggerListeners()\n#11 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#12 /var/lib/monarc/fo/public/index.php(34): Laminas\\Mvc\\Application->run()\n#13 {main}"
}
}
]
}
```

**Expected behavior**
The JSON export should be returned.

**Desktop (please complete the following information):**

MONARC 2.12.0 and 2.12.1

**Comment by cedricbonhomme** [comment]
monarc-project/zm-core/pull/61
