### ISSUE TITLE
why it occurs??

### ISSUE THREAD

**Issue by Coderyang666666** [monarc-project/MonarcAppFO#526]
[Fri Mar 15 18:27:01.621343 2024] [php:notice] [pid 1052] [client ::1:31335] PHP Fatal error:  Uncaught Error: Call to a member function has() on null in /home/yanghang/vendor/laminas/laminas-modulemanager/src/Listener/ServiceListener.php:198\nStack trace:\n#0 /home/yanghang/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\\ModuleManager\\Listener\\ServiceListener->onLoadModulesPost()\n#1 /home/yanghang/vendor/laminas/laminas-eventmanager/src/EventManager.php(169): Laminas\\EventManager\\EventManager->triggerListeners()\n#2 /home/yanghang/vendor/laminas/laminas-modulemanager/src/ModuleManager.php(109): Laminas\\EventManager\\EventManager->triggerEvent()\n#3 /home/yanghang/vendor/laminas/laminas-mvc/src/Application.php(261): Laminas\\ModuleManager\\ModuleManager->loadModules()\n#4 /home/yanghang/public/index.php(55): Laminas\\Mvc\\Application::init()\n#5 {main}\n  thrown in /home/yanghang/vendor/laminas/laminas-modulemanager/src/Listener/ServiceListener.php on line 198

**Comment by Coderyang666666** [comment]
if (! $this->defaultServiceManager->has($sm['service_manager']))

**Comment by ruslanbaidan** [comment]
Please, provide more context on: where it happens (env) and how and to reproduce.
In general this is the application dependencies issue, not related to the app itself and can be solved by a proper installation.
